baseURL = "https://sysadmin.info.pl/"
title = "SYSADMIN"
theme = ["hugo-embed-pdf-shortcode", "zzo"]

enableInlineShortcodes = true

viewportSize = "normal"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
hasCJKLanguage = false

summaryLength = 70
buildFuture = true

copyright = "&copy;{year}, [sysadmin](https://sysadmin.info.pl/) - All rights reserved"
timeout = 10000
enableEmoji = true
paginate = 11
rssLimit = 100

enableGitInfo = false
googleAnalytics = ""

ignoreErrors = ["error-output-taxonomy"]  # Add this line here

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = true
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = true
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
    [languages.en.params]
      languagedir = "ltr"
  [languages.pl]
    languageName = "Polish"
    contentDir = "content/pl"
    weight = 2
    [languages.pl.params]
      languagedir = "ltr"
