[en]
  title = "Sysadmin - Linux administration, security and hardening"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[pl]
  title = "Sysadmin - Administracja serwerami opartymi o dystrybucje Linux."
  languageName = "Polski"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/pl"
