[en]
  title = "Sysadmin - Linux administration, security and hardening"
  languageName = "English"
  weight = 1
  contentdir = "content/en"
  [en.params]
    languagedir = "ltr"

[pl]
  title = "Sysadmin - Administracja serwerami opartymi o dystrybucje Linux."
  languageName = "Polski"
  weight = 2
  contentdir = "content/pl"
  [pl.params]
    languagedir = "ltr"