[[main]]
  identifier = "about"
  name = "O mnie"
  url = "about"
  weight = 1

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 2

[[main]]
  identifier = "contact"
  name = "Kontakt"
  url = "contact"
  weight = 3
