[[main]]
  identifier = "about"
  name = "About me"
  url = "about"
  weight = 1

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 2

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 3
