[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.111.3"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "sysadmin.info.pl"
      Content-Security-Policy = "default-src 'none'; style-src 'self' 'unsafe-inline'; script-src 'unsafe-hashes' 'sha256-{RFWPLDbv2BY+rCkDzsE+0fr8ylGr2R2faWMhq4lfEQc=}'; connect-src 'self'; img-src 'self' data:image/svg+xml; font-src 'self'; manifest-src 'https://sysadmin.info.pl/manifest.json';"
